spellchecker: aspell
jobs: 8

matrix:
- name: Markdown
  aspell:
    lang: pt_BR
  dictionary:
    wordlists:
    - wordlist.txt
    output: wordlist.dic
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  sources:
  - '**/*.md'
  default_encoding: utf-8
