spellchecker: aspell
jobs: 8

matrix:
- name: md
  hunspell:
    d: docs/src/dictionary/hunspell/pt_BR
  aspell:
    lang: pt
    d: pt_BR
  sources:
  - '**/*.md'
  default_encoding: utf-8
  report:
    format: html
    path: spell-check-report/report.html
