spellchecker: aspell

matrix:
- name: Prompts
  aspell:
    lang: pt_BR
  dictionary:
    wordlists:
    - .prompt_dic.txt
    ouput: build/.prompt_dic.dic
    encoding: utf-8
  sources:
  - '**/**/*.md'
  default_encoding: utf-8
