spellchecker: aspell
jobs: 8

matrix:
- name: Markdown
  aspell:
    lang: pt
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
    comments: false
    ignores:
    - code
    - pre
  sources:
  - '**/*.md'
  default_encoding: utf-8
