spellchecker: aspell
jobs: 8

matrix:
- name: txt
  hunspell:
    d: docs/src/dictionary/hunspell/pt_BR
  aspell:
    lang: pt
    d: pt_BR

matrix:
- name: txt
  aspell:
    lang: pt
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
    comments: false
    ignores:
    - code
    - pre
  sources:
  - '**/*.md'
  default_encoding: utf-8
  report:
    format: html
    path: spell-check-report/report.html
