name: CI

on:
    push:
        branches:
            -  "main"
    pull_request:
        branches:
            -  "main"

    workflow_dispatch:

jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyspelling
    - name: Install Aspell
      run: |
        sudo apt-get update
        sudo apt-get install -y aspell aspell-pt
    - name: Build documents
      run: |
    - name: Spell check
      run: |
        python -m pyspelling -vvvv
