name: CI

on:
    push:
        branches:
            - "main"
    pull_request:
        branches:
            - "main"
    workflow_dispatch:

jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.2
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyspelling
    - name: Install Aspell
      run: |
        sudo apt-get update
        sudo apt-get install -y aspell aspell-pt
    - name: Install AWK
      run: |
        sudo apt-get install gawk
    - name: Get Diff
      run: |
        git diff --name-only head HEAD^ | tee diff.txt
    - name: Spell check
      run: |
        awk '{printf "-S \"%s\" ", $0}' diff.txt | xargs -I {} sh -c 'python -m pyspelling -v {}' | tee spelling_output.txt

    - name: Upload Spell Check Output
      uses: actions/upload-artifact@v4
      with:
        name: spelling_output
        path: |
          spelling_output.txt
          diff.txt
