name: CI

on:
    push:
        branches:
            - "main"
    pull_request:
        branches:
            - "main"

    workflow_dispatch:

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    # The checkout step
    - uses: actions/checkout@v3
    - name: Install Aspell
      run: |
        sudo apt-get update
        sudo apt-get install -y aspell aspell-pt
    - uses: rojopolis/spellcheck-github-actions@0.40.0
      name: Spellcheck
      with:
        source_files: '**/*.md'
        task_name: Markdown
        output_file: spellcheck-output.txt
    - uses: actions/upload-artifact@v4
      if: '!cancelled()' # Do not upload artifact if job was cancelled
      with:
        name: Spellcheck Output
        path: spellcheck-output.txt
